### PR TITLE
restoring production manifest.yml

### PR DESCRIPTION
**Pull request by nfriedly**

### CODE REVIEW

**Comment by germanattanasio** [comment]
I think bluemix sets `NODE_ENV=production` automatically. my bad I forgot to update the app name :(

**Comment by nfriedly** [comment]
Really? That must be new.

**Comment by nfriedly** [comment]
From the apps I've just looked at, I only ever see `NODE_ENV` set in user-provided env variables

**Comment by germanattanasio** [comment]
I used to set it but it's being set to production but bluemix after the
last update to the buildpack.

Source:
https://developer.ibm.com/bluemix/2016/02/04/node-js-buildpack-v30-updates/

**Comment by nfriedly** [comment]
Cool. I guess the things I checked must have had the older buildpack.

**Pull request merged**
