### PR TITLE
Breaks /api calls out into seperate route

### PR DESCRIPTION
**Pull request by kognate**
Now the app.js file isn't the only place for the routes. This
commit breaks out the api calls into a seperate route file.

### CODE REVIEW

**Comment by germanattanasio** [comment]
beautiful. I imagine that you tested classifying an image and creating a classifier and everything was working.

**Comment by kognate** [comment]
Works On My Machine.  I'm also targeting all these changes into the `sprint8` branch, which I'll setup to deploy to staging (but I want to talk to you about that first).

**Comment by germanattanasio** [comment]
do you want this PR to be merged ?

**Comment by kognate** [comment]
Yes,  this PR can be merged (it's should be merged into sprint8).

**Pull request merged**
